"""Pydantic models for data validation.

These models are used to validate data before database writes.
They will be extended in later phases as more entities are needed.
"""

from typing import Literal

from pydantic import BaseModel


class CourseRecord(BaseModel):
    """Validates a course row before insertion into the courses table."""

    course_id: int
    course_name: str
    summary_text: str | None = None


class UserRecord(BaseModel):
    """Validates a user row before insertion into the users table."""

    portal_id: int
    grade: int | None = None
    employee_type: str | None = None
    training_goal: float | None = None
    country: str | None = None
    emp_practise: str | None = None
    manager_portalid: int | None = None
    hireddate: str | None = None  # ISO date string after conversion


class CompletionRecord(BaseModel):
    """Validates a completion row before insertion into the course_completions table."""

    portal_id: int
    course_id: int
    enrolment_date: str  # ISO datetime string, required (part of PK)
    completion_status: str | None = None
    completed_date: str | None = None  # ISO datetime string


class CourseSkill(BaseModel):
    """A single skill extracted from a course summary by LLM."""

    skill_name: str
    skill_level: Literal["beginner", "intermediate", "advanced"]
    skill_confidence: float
    topic_name: str
    topic_weight: float


class CourseSkillsResponse(BaseModel):
    """Container for LLM structured output -- wraps list of CourseSkill."""

    skills: list[CourseSkill]


class CoursePrerequisite(BaseModel):
    """A single prerequisite extracted from a course summary by LLM."""

    prereq_name: str
    relevance_strength: float
    reason_short: str
    prereq_confidence: float


class CoursePrerequisitesResponse(BaseModel):
    """Container for LLM structured output -- wraps list of CoursePrerequisite."""

    prerequisites: list[CoursePrerequisite]


class UserSkillInferred(BaseModel):
    """A skill inferred from a user's course completion history."""

    skill_name: str
    skill_level: str
    skill_confidence: float
    topic_name: str


class RequiredSkill(BaseModel):
    """A skill required to achieve a learning goal, extracted by LLM."""

    skill_name: str
    skill_level: Literal["beginner", "intermediate", "advanced"]
    importance: float


class GoalSkillsResponse(BaseModel):
    """Container for LLM structured output -- wraps list of RequiredSkill."""

    skills: list[RequiredSkill]


class SkillGap(BaseModel):
    """A single skill gap between user state and goal requirement."""

    skill_name: str
    required_level: str
    current_level: str | None = None
    gap_type: Literal["missing", "weak"]
    priority: float


class SkillGapReport(BaseModel):
    """Complete gap analysis result."""

    gaps: list[SkillGap]
    total_required: int


class UserContext(BaseModel):
    """User profile + completion history + inferred skills."""

    portal_id: int
    grade: int | None = None
    employee_type: str | None = None
    training_goal: float | None = None
    country: str | None = None
    completed_course_ids: list[int] = []
    completed_course_names: list[str] = []
    inferred_skills: list[UserSkillInferred] = []


class CandidateCourse(BaseModel):
    """A course candidate returned by hybrid retrieval."""

    course_id: int
    course_name: str
    score: float
    source: str
    matched_skills: list[str] = []
    summary_text: str | None = None


class RetrievalResult(BaseModel):
    """Aggregated result from hybrid retrieval (BM25 + semantic)."""

    candidates: list[CandidateCourse]
    bm25_count: int
    semantic_count: int
    both_count: int


class PlannedCourse(BaseModel):
    """A single course selected for the learning plan by the LLM."""

    course_id: int
    course_name: str
    targeted_skills: list[str]
    targeted_topic: str
    targeted_level: str
    phase: str
    course_order: int
    estimated_duration_hours: float
    reasoning_summary: str


class LearningPlanResponse(BaseModel):
    """Complete learning plan generated by the LLM."""

    courses: list[PlannedCourse]
    total_estimated_hours: float
    skill_coverage_summary: str


class ValidationViolation(BaseModel):
    """A single validation violation found in a learning plan."""

    check_name: str  # e.g., "prerequisite_ordering", "hour_budget", "skill_coverage"
    severity: str  # "error" or "warning"
    message: str  # Human-readable description of the violation
    course_id: int | None = None  # Optional: which course is involved


class ValidationResult(BaseModel):
    """Result of validating a learning plan against constraints."""

    is_valid: bool
    violations: list[ValidationViolation] = []
    iteration: int = 0  # Which validation iteration produced this result
